### ISSUE TITLE
Some pointers on how to (cross?) compile this code?

### ISSUE THREAD

**Issue by rdvdijk** [warhammerkid/ruby-audio#5]
Hi warhammerkid,

I am trying to run the `rake gems` command, which apparently cross-compiles all the code. I installed MinGW for OS X.

This fails on OS X, because the FLAC headers cannot be found (but are installed on my machine using homebrew) when compiling `libsndfile`. Here is the first line with an error from `tmp/i386-mingw32/ports/libsndfile/1.0.24/compile.log`.

```
    CC     flac.lo
    flac.c:34:33: error: FLAC/stream_decoder.h: No such file or directory
```

Can you give some pointers how to build this project? Should I just ignore the Rakefile altogether if I want to build it for my own system?

Thanks,
Roel

**Comment by warhammerkid** [comment]
I didn't have the flac libraries installed on my system and it worked just fine, so it's probably finding them when it shouldn't and trying to compile the flac support. That said, as long as you don't need to support Windows with the gems you generate, you don't need to worry about the cross compiling. Just run `rake gem` rather than `rake gems`.

**Comment by rdvdijk** [comment]
Ah thanks, that works just fine. I still need a MinGW environment to run any `rake` task, by the way.
