### ISSUE TITLE
using gem in vendor

### ISSUE THREAD

**Issue by casiodk** [warhammerkid/ruby-audio#6]
Hi, I´ve copied the gem in the vendor folder for use on heroku, but gets this error message when i try to use it with the waveform gem

ruby-audio-1.6.1/lib/ruby-audio.rb:6:in `require': no such file to load -- rubyaudio_ext (LoadError)

Any suggestions to a solution?

**Comment by warhammerkid** [comment]
ruby-audio is a "native" extension, which means it has parts that need to be compiled for the computer it's going to be running on. It looks like you can pre-compile native extensions on the appropriate version of debian and copy them over (http://stackoverflow.com/questions/3104238/how-do-you-package-extensions-for-heroku), but that won't work for ruby-audio because it requires libsndfile to also be installed.

I would talk to heroku support and see what they suggest that you do.
